---
- hosts: localhost
  gather_facts: no
  vars:
#    kiosk_urls: "https://opensource.com/open-organization/resources/book-series https://opensource.com/open-organization/resources/open-org-definition https://opensource.com/open-organization/resources/open-decision-framework"
    kiosk_urls: "https://heise.de"
#  vars_files:
#    - /root/kiosk_vars.yml
  roles:
#    - { role: ansible-role-base_setup }
    - { role: ansible-role-kiosk }
