---
# tasks file for role kiosk

- name: Ensure required packages are installed
  package:
    name: vim,chromium-browser,unclutter,xdotool
    state: present
  tags: kiosk

- name: Ensure group "kiosk" exists
  group:
    name: kiosk
    state: present
  tags: kiosk

- name: Add the user 'kiosk' and corresponding group
  user:
    name: kiosk
    comment: Kiosk
    group: kiosk
  tags: kiosk

- name: Setup autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regex: "^autologin-user=.*"
    line: "autologin-user=kiosk"
  tags: kiosk

- name: Install kiosk.sh script
  template:
    src: kiosk.sh.jp2
    dest: /home/kiosk/kiosk.sh
    mode: u=rwx
  tags: kiosk

- name: Create directory if it does not exist
  file:
    path: /home/kiosk/.config/autostart
    state: directory
    mode: u=rwx
  tags: kiosk

- name: Install kiosk.desktop script
  template:
    src: kiosk.desktop.jp2
    dest: /home/kiosk/.config/autostart/kiosk.desktop
    mode: u=rw,g=r,o=r
  tags: kiosk

- name: Install kiosk.urls script
  template:
    src: kiosk.urls.jp2
    dest: /home/kiosk/kiosk.urls
    mode: u=rw,g=rw,o=r
  tags: kiosk
